// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: staedte.proto

package stadtservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StadtInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=locationId,proto3" json:"locationId,omitempty"`
	Stadtname     string                 `protobuf:"bytes,2,opt,name=stadtname,proto3" json:"stadtname,omitempty"`
	Postleitzahl  string                 `protobuf:"bytes,3,opt,name=postleitzahl,proto3" json:"postleitzahl,omitempty"`
	Breitengrad   float64                `protobuf:"fixed64,4,opt,name=breitengrad,proto3" json:"breitengrad,omitempty"`
	Langengrad    float64                `protobuf:"fixed64,5,opt,name=langengrad,proto3" json:"langengrad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StadtInfo) Reset() {
	*x = StadtInfo{}
	mi := &file_staedte_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StadtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StadtInfo) ProtoMessage() {}

func (x *StadtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staedte_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StadtInfo.ProtoReflect.Descriptor instead.
func (*StadtInfo) Descriptor() ([]byte, []int) {
	return file_staedte_proto_rawDescGZIP(), []int{0}
}

func (x *StadtInfo) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *StadtInfo) GetStadtname() string {
	if x != nil {
		return x.Stadtname
	}
	return ""
}

func (x *StadtInfo) GetPostleitzahl() string {
	if x != nil {
		return x.Postleitzahl
	}
	return ""
}

func (x *StadtInfo) GetBreitengrad() float64 {
	if x != nil {
		return x.Breitengrad
	}
	return 0
}

func (x *StadtInfo) GetLangengrad() float64 {
	if x != nil {
		return x.Langengrad
	}
	return 0
}

type PostleitzahlenSuchbegriff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plzprefix     string                 `protobuf:"bytes,1,opt,name=plzprefix,proto3" json:"plzprefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostleitzahlenSuchbegriff) Reset() {
	*x = PostleitzahlenSuchbegriff{}
	mi := &file_staedte_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostleitzahlenSuchbegriff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostleitzahlenSuchbegriff) ProtoMessage() {}

func (x *PostleitzahlenSuchbegriff) ProtoReflect() protoreflect.Message {
	mi := &file_staedte_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostleitzahlenSuchbegriff.ProtoReflect.Descriptor instead.
func (*PostleitzahlenSuchbegriff) Descriptor() ([]byte, []int) {
	return file_staedte_proto_rawDescGZIP(), []int{1}
}

func (x *PostleitzahlenSuchbegriff) GetPlzprefix() string {
	if x != nil {
		return x.Plzprefix
	}
	return ""
}

type Postleitzahl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postleitzahl  string                 `protobuf:"bytes,1,opt,name=postleitzahl,proto3" json:"postleitzahl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Postleitzahl) Reset() {
	*x = Postleitzahl{}
	mi := &file_staedte_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Postleitzahl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Postleitzahl) ProtoMessage() {}

func (x *Postleitzahl) ProtoReflect() protoreflect.Message {
	mi := &file_staedte_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Postleitzahl.ProtoReflect.Descriptor instead.
func (*Postleitzahl) Descriptor() ([]byte, []int) {
	return file_staedte_proto_rawDescGZIP(), []int{2}
}

func (x *Postleitzahl) GetPostleitzahl() string {
	if x != nil {
		return x.Postleitzahl
	}
	return ""
}

type StadtSuchbegriff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stadtname     string                 `protobuf:"bytes,1,opt,name=stadtname,proto3" json:"stadtname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StadtSuchbegriff) Reset() {
	*x = StadtSuchbegriff{}
	mi := &file_staedte_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StadtSuchbegriff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StadtSuchbegriff) ProtoMessage() {}

func (x *StadtSuchbegriff) ProtoReflect() protoreflect.Message {
	mi := &file_staedte_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StadtSuchbegriff.ProtoReflect.Descriptor instead.
func (*StadtSuchbegriff) Descriptor() ([]byte, []int) {
	return file_staedte_proto_rawDescGZIP(), []int{3}
}

func (x *StadtSuchbegriff) GetStadtname() string {
	if x != nil {
		return x.Stadtname
	}
	return ""
}

type Stadtname struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stadtname     string                 `protobuf:"bytes,1,opt,name=stadtname,proto3" json:"stadtname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stadtname) Reset() {
	*x = Stadtname{}
	mi := &file_staedte_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stadtname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stadtname) ProtoMessage() {}

func (x *Stadtname) ProtoReflect() protoreflect.Message {
	mi := &file_staedte_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stadtname.ProtoReflect.Descriptor instead.
func (*Stadtname) Descriptor() ([]byte, []int) {
	return file_staedte_proto_rawDescGZIP(), []int{4}
}

func (x *Stadtname) GetStadtname() string {
	if x != nil {
		return x.Stadtname
	}
	return ""
}

var File_staedte_proto protoreflect.FileDescriptor

const file_staedte_proto_rawDesc = "" +
	"\n" +
	"\rstaedte.proto\x12\x13stadteInformationen\"\xaf\x01\n" +
	"\tStadtInfo\x12\x1e\n" +
	"\n" +
	"locationId\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1c\n" +
	"\tstadtname\x18\x02 \x01(\tR\tstadtname\x12\"\n" +
	"\fpostleitzahl\x18\x03 \x01(\tR\fpostleitzahl\x12 \n" +
	"\vbreitengrad\x18\x04 \x01(\x01R\vbreitengrad\x12\x1e\n" +
	"\n" +
	"langengrad\x18\x05 \x01(\x01R\n" +
	"langengrad\"9\n" +
	"\x19PostleitzahlenSuchbegriff\x12\x1c\n" +
	"\tplzprefix\x18\x01 \x01(\tR\tplzprefix\"2\n" +
	"\fPostleitzahl\x12\"\n" +
	"\fpostleitzahl\x18\x01 \x01(\tR\fpostleitzahl\"0\n" +
	"\x10StadtSuchbegriff\x12\x1c\n" +
	"\tstadtname\x18\x01 \x01(\tR\tstadtname\")\n" +
	"\tStadtname\x12\x1c\n" +
	"\tstadtname\x18\x01 \x01(\tR\tstadtname2\xc2\x03\n" +
	"\x13StadteInformationen\x12w\n" +
	" SucheNachAnteilEinerPostleitzahl\x12..stadteInformationen.PostleitzahlenSuchbegriff\x1a!.stadteInformationen.Postleitzahl0\x01\x12i\n" +
	"\x1eSucheNachAnteilEinesStadtnamen\x12%.stadteInformationen.StadtSuchbegriff\x1a\x1e.stadteInformationen.Stadtname0\x01\x12d\n" +
	"\x19SucheNachExakenStadtnamen\x12%.stadteInformationen.StadtSuchbegriff\x1a\x1e.stadteInformationen.StadtInfo0\x01\x12a\n" +
	"\x1cSucheNachExtakerPostleitzahl\x12!.stadteInformationen.Postleitzahl\x1a\x1e.stadteInformationen.StadtInfoB\x0fZ\r/stadtserviceb\x06proto3"

var (
	file_staedte_proto_rawDescOnce sync.Once
	file_staedte_proto_rawDescData []byte
)

func file_staedte_proto_rawDescGZIP() []byte {
	file_staedte_proto_rawDescOnce.Do(func() {
		file_staedte_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staedte_proto_rawDesc), len(file_staedte_proto_rawDesc)))
	})
	return file_staedte_proto_rawDescData
}

var file_staedte_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_staedte_proto_goTypes = []any{
	(*StadtInfo)(nil),                 // 0: stadteInformationen.StadtInfo
	(*PostleitzahlenSuchbegriff)(nil), // 1: stadteInformationen.PostleitzahlenSuchbegriff
	(*Postleitzahl)(nil),              // 2: stadteInformationen.Postleitzahl
	(*StadtSuchbegriff)(nil),          // 3: stadteInformationen.StadtSuchbegriff
	(*Stadtname)(nil),                 // 4: stadteInformationen.Stadtname
}
var file_staedte_proto_depIdxs = []int32{
	1, // 0: stadteInformationen.StadteInformationen.SucheNachAnteilEinerPostleitzahl:input_type -> stadteInformationen.PostleitzahlenSuchbegriff
	3, // 1: stadteInformationen.StadteInformationen.SucheNachAnteilEinesStadtnamen:input_type -> stadteInformationen.StadtSuchbegriff
	3, // 2: stadteInformationen.StadteInformationen.SucheNachExakenStadtnamen:input_type -> stadteInformationen.StadtSuchbegriff
	2, // 3: stadteInformationen.StadteInformationen.SucheNachExtakerPostleitzahl:input_type -> stadteInformationen.Postleitzahl
	2, // 4: stadteInformationen.StadteInformationen.SucheNachAnteilEinerPostleitzahl:output_type -> stadteInformationen.Postleitzahl
	4, // 5: stadteInformationen.StadteInformationen.SucheNachAnteilEinesStadtnamen:output_type -> stadteInformationen.Stadtname
	0, // 6: stadteInformationen.StadteInformationen.SucheNachExakenStadtnamen:output_type -> stadteInformationen.StadtInfo
	0, // 7: stadteInformationen.StadteInformationen.SucheNachExtakerPostleitzahl:output_type -> stadteInformationen.StadtInfo
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_staedte_proto_init() }
func file_staedte_proto_init() {
	if File_staedte_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staedte_proto_rawDesc), len(file_staedte_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staedte_proto_goTypes,
		DependencyIndexes: file_staedte_proto_depIdxs,
		MessageInfos:      file_staedte_proto_msgTypes,
	}.Build()
	File_staedte_proto = out.File
	file_staedte_proto_goTypes = nil
	file_staedte_proto_depIdxs = nil
}
